-- Esquema PostgreSQL para Supabase.
-- Ejecutar completo desde Supabase Dashboard > SQL Editor.
-- Este archivo conserva IDs numéricos para mantener compatibilidad con la API actual.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  role text NOT NULL DEFAULT 'usuario'
    CHECK (role IN ('usuario', 'entrenador', 'administrador')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  weight numeric(6,2),
  target_weight numeric(6,2),
  height numeric(4,2),
  objective varchar(120),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.weight_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  weight numeric(6,2) NOT NULL,
  recorded_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, recorded_date)
);

CREATE INDEX IF NOT EXISTS idx_weight_history_user
  ON public.weight_history(user_id);

CREATE TABLE IF NOT EXISTS public.custom_exercises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name varchar(160) NOT NULL,
  type varchar(80) NOT NULL,
  muscle varchar(120) NOT NULL,
  difficulty varchar(80) NOT NULL,
  equipment varchar(160) NOT NULL,
  instructions text NOT NULL,
  safety_info text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_custom_exercises_user
  ON public.custom_exercises(user_id);

CREATE TABLE IF NOT EXISTS public.trainer_user_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  assigned_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trainer_assignments_trainer
  ON public.trainer_user_assignments(trainer_id);

CREATE TABLE IF NOT EXISTS public.routines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title varchar(160) NOT NULL,
  level varchar(60) NOT NULL,
  duration_minutes smallint NOT NULL DEFAULT 0
    CHECK (duration_minutes >= 0),
  scheduled_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_routines_trainer
  ON public.routines(trainer_id);

CREATE INDEX IF NOT EXISTS idx_routines_user
  ON public.routines(user_id);

CREATE TABLE IF NOT EXISTS public.routine_exercises (
  routine_id bigint NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  exercise_id bigint NOT NULL REFERENCES public.custom_exercises(id) ON DELETE CASCADE,
  exercise_order smallint NOT NULL DEFAULT 1
    CHECK (exercise_order > 0),
  PRIMARY KEY (routine_id, exercise_id)
);

CREATE INDEX IF NOT EXISTS idx_routine_exercises_exercise
  ON public.routine_exercises(exercise_id);

CREATE TABLE IF NOT EXISTS public.routine_completions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  routine_id bigint NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  completed_at timestamptz NOT NULL DEFAULT now(),
  total_exercises smallint NOT NULL DEFAULT 0
    CHECK (total_exercises >= 0)
);

CREATE INDEX IF NOT EXISTS idx_routine_completions_routine
  ON public.routine_completions(routine_id);

CREATE INDEX IF NOT EXISTS idx_routine_completions_user
  ON public.routine_completions(user_id);

CREATE TABLE IF NOT EXISTS public.exercise_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completion_id bigint NOT NULL REFERENCES public.routine_completions(id) ON DELETE CASCADE,
  routine_id bigint NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  exercise_id bigint REFERENCES public.custom_exercises(id) ON DELETE SET NULL,
  exercise_name varchar(160) NOT NULL,
  exercise_type varchar(80) NOT NULL,
  weight_kg numeric(7,2),
  duration_minutes numeric(7,2),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_exercise_logs_completion
  ON public.exercise_logs(completion_id);

CREATE INDEX IF NOT EXISTS idx_exercise_logs_routine
  ON public.exercise_logs(routine_id);

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS user_progress_set_updated_at ON public.user_progress;
CREATE TRIGGER user_progress_set_updated_at
BEFORE UPDATE ON public.user_progress
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- El backend actual usa su propia autenticación JWT y accede a estas tablas.
-- Si vas a consultar Supabase directamente desde el frontend, habilita RLS
-- y crea políticas específicas antes de exponer estas tablas públicamente.
